import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers
          attribute="class"
          defaultTheme="dark"
          enableSystem
          themes={[
            "light",
            "dark",
            "red",
            "red-dark",
            "green",
            "green-dark",
            "dracula",
            "dracula-dark",
            "gold",
            "gold-dark",
            "azarath",
            "azarath-dark",
            "poimandres",
            "poimandres-dark",
            "discord",
            "discord-dark",
            "adj",
            "adj-dark",
            "soft-purple",
            "soft-purple-dark",
            "umbra-protocol",
            "min-light",
            "min-dark",
            "aura-dark",
            "pro-hacker",
            "tokyo-city-lighter",
            "ayu-light-bordered",
          ]}
        >
          <main className="flex overflow-x-hidden overflow-y-auto text-foreground bg-background h-screen w-screen ">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
